spring.application.name=demo

# PostgreSQL Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/telemetry_db
spring.datasource.username=devuser
spring.datasource.password=devpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA Settings
# "update" means that Hibernate will automatically create or update the database schema based on the entity classes
spring.jpa.hibernate.ddl-auto=update
# Show SQL statements in the console for debugging purposes
spring.jpa.show-sql=true